version: "3.7"
services:
  node:
    image: lab2-p2p
    build: .
    working_dir: /files
    volumes:
      - C:\Repos\PeerToPeerFileShare\node1:/files/
    env_file:
      - ./.env
    networks:
      net:
        ipv4_address: 172.19.1.2
        ipv6_address: "2001:3984:3989::10"

  node2:
    image: lab2-p2p
    build: .
    working_dir: /files
    volumes:
      - C:\Repos\PeerToPeerFileShare\node2:/files/
    env_file:
      - ./.env
    depends_on:
      - node
    networks:
      net:
        ipv4_address: 172.19.1.3
        ipv6_address: "2001:3984:3989::11"
        
networks:
  net:
    driver: bridge
    driver_opts:
            com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.19.1.0/20
      - subnet: "2001:3984:3989::/64"

  # node3:
  #   image: lab2-p2p
  #   build: .
  #   working_dir: /files
  #   volumes:
  #     - C:\Repos\PeerToPeerFileShare\node3:/files/
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - node
  #     - node2
  #   networks:
  #     net:
  #       ipv4_address: 172.19.1.4
  #       ipv6_address: "2001:3984:3989::12"

  # node4:
  #   image: lab2-p2p
  #   build: .
  #   working_dir: /files
  #   volumes:
  #     - C:\Repos\PeerToPeerFileShare\node4:/files/
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - node
  #     - node2
  #     - node3
  #   networks:
  #     net:
  #       ipv4_address: 172.19.1.5
  #       ipv6_address: "2001:3984:3989::13"

  # showActiveTcp:
  #   image: showactivetcp
  #   build: .
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - node
  #     - node2
  #   networks:
  #     net:
  #       ipv4_address: 172.19.1.4
  #       ipv6_address: "2001:3984:3989::12"

